### ISSUE TITLE
Class declaration vs typescript interface for DTOs

### ISSUE THREAD

**Issue by tony3918** [NovaLabDev/IRinger#8]
현재 codebase에서는 DTO를 `class` declaration으로 정의하고 있습니다. 그러나 js에서의 class는 Java나 python에서와 같은 OOP가 아니고 단순히 object creation을 위한 syntactic sugar입니다. 따라서 DTO의 object 형태를 정의하기 위해 불필요하게 class 문법을 쓰기보다 typescript `interface`로서 각각의 DTO type을 정의하고 함수의 인자를 알맞게 typing 하는 것을 제안드립니다.

관련 slack 논의
- https://shinsungtk.slack.com/archives/C019B2CRFV4/p1604109499109900
- https://shinsungtk.slack.com/archives/C019B2CRFV4/p1604110184115600

**Comment by jbjeong-sstk** [comment]
class로 오브젝트 만들면, constractor 활용도하고 {} 리터럴로 오브제트 만드는것보다 가독성이 좋아 달콤한데, 추후 어떤 독이 될까요?

**Comment by tony3918** [comment]
1. DTO들은 mapping object로써 쓰일 뿐이지 전통적인 OOP language의 class가 갖는 성질을 갖지 않습니다.
지금 저희 codebase 내의 DTO들은 java로 치면 POJO로써 get, set만 사용되고 있는 것이지, 그 외에 어떤 internal state이나 method를 갖고 있는 것이 아닙니다. 그래서 단순히 object creation만을 위해 class 문법을 써서 갖는 장점이 무엇인지 모르겠고, 오히려 추후 혼란을 일으킬 것 같습니다.

2. Class의 constructor를 활용한다고 하셨슨데, 90% 이상의 경우 DTO의 constructor는 단순한 mapping function에 불과할 것 같습니다.
현재 코드 내의 constructor들도 전부 `this.a = a;` 식으로 constructor argument를 instance에 mapping 해주기만 합니다. 앞으로 추가될 대부분의 DTO constructor들도 마찬가지일 것으로 예상되는데, 직접 object creation을 하는 것에 비해 불필요한 코드를 들고갈 이유가 없다고 생각합니다. 게다가 typescript interface는 js로 build 될 때 code에 포함되지도 않기 때문에 실제 코드량은 0인 반면 class를 쓸 경우 그 밑에서 실행되는 모든 `Object.create`, `Object.setPrototypeOf` 같은 코드들이 전부 포함될 것입니다.
```
// Interface -> 나중에 ts build 시 제외됨
interface RingerCreateDto {
  sn: string;
  name: string;
  groupId: string;
  accountId?: string;
  ivInfo: IVInfoCrtDto;
}

// Class -> build code에 그대로 포함됨
class RingerCreateDto {
  constructor(accountId: string | undefined) {
    this.sn = '';
    this.name = '';
    this.groupId = '';
    this.groupName = '';
    this.accountId = accountId;
    this.ivInfo = new IVInfoCrtDto(100, 30, 3.1);
  }
  accountId: string | undefined;
  groupId: string;
  groupName: string;
  sn: string | undefined;
  name: string | undefined;
  ivInfo: IVInfoCrtDto;
}
```
3. 단순 mapping이 아니고 추가적인 business logic이 존재하는 소수의 DTO에 대해서만 필요에 따라 creator utility function를 만들면 됩니다.
```
// Business logic이 존재하는 dto에 대한 creator utility function 예시
const getLoginDto = (email: string, password: string) => {
  const hash = hashFunction(password);
  return {
    email,
    hash
  }
}
```
4. 가독성에 대한 부분은 개발자의 취향에 따라 다를 수 있겠지만 object 만들 때의 코드가 더 길어질 이유는 없을 것 같습니다. 다음 예시처럼 둘 간에 코드 길이는 거의 차이가 없을텐데, 제가 어디선가 잘못 이해하고 있나요?
```
// Class 사용 시
const editDto = new RingerCreateDto(user?.uid);
editDto.name = editRinger?.name || '';
editDto.sn = editRinger?.sn || '';
editDto.groupId = editRinger?.group._id || '';
editDto.groupName = editRinger?.group.name || '';
setCreateDto(editDto);

// Interface 사용 시
setCreateDto({
  accountId: user?.uid,
  name: editRinger?.name || '',
  sn: editRinger?.sn || '',
  groupId: editRinger?.group._id || '',
  groupName: editRinger?.group.name || '',
});
```

**Comment by jbjeong-sstk** [comment]
Data Transfer Object를 {} 로하냐, class 로 하냐인데....

1 답변] dto의 중요 역할을 mapping 이라고 봤네요.
{} 생성 한 것도 object이니(추상화, 캡슐화, 상속, 다형성)를 구현 할 려면 할 수(?) 있을 것이고...
암튼 class 문법을 써서 장점은([이제 class에서 private도 쓴다네요; 이건 뭐.. 암튼 지금 말하는 장점은 아니고](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Classes/Private_class_fields))

```
const editDto = new RingerUpdateDto(editRinger);
setUpdateDto(editDto);

// Interface 사용 시. ==> setDto 할때마다 {} 선언이 들어가야 한는데 -> class는 new Duo() 로 간단히 쓸 수 있지 않을까요?
setCreateDto({
  accountId: user?.uid,
  name: editRinger?.name || '',
  sn: editRinger?.sn || '',
  groupId: editRinger?.group._id || '',
  groupName: editRinger?.group.name || '',
});


// Class 선언
class RingerUpdateDto {
  contractor(editRinger: Ringer) {
    editDto.name = editRinger?.name || '';
    editDto.sn = editRinger?.sn || '';
    editDto.groupId = editRinger?.group._id || '';
    editDto.groupName = editRinger?.group.name || '';
  }
}
```

> 오히려 추후 혼란
음.. 어떤 혼란이 있을까요?... : [javascript class는 setter/getter](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/set) 사용이 java랑 달라 조심해야 하는데. 또한 문법 슈가라는 말이 있고 함수형 프로그래밍에 반 한다하여 저도 아직까지는 mapping 용으로만 쓰고 싶습니다.

```
const getUpdateDto = (editRinger: Ringer): RingerUpdateDto => {
  return {
    editDto.name = editRinger?.name || '';
    editDto.sn = editRinger?.sn || '';
    editDto.groupId = editRinger?.group._id || '';
    editDto.groupName = editRinger?.group.name || '';
  }
}
```
글 쓰면서 드는 생각이, 현석님 글 3번처럼 위 코드처럼 utility function 을 써서 하면 좋겠네요..
JS에서 함수도 객체라 함수로 데이터 OOP 를 할 수 있을 것 같고(프로젝트가 복잡해지고 커지면서 dto가 커지고 복잡해 지더라구요)
```
export class CreateActivityAdvancedDto implements ActivityAdvancedDto {
  constructor() {
    this.displayName = DisplayName.ANONYMOUS;
    this.point = 0;
    this.numberOfVoice = 0;
    this.voteType = VoteType.SINGLE;
    this.tallyTiming = TallyTiming.ANY;
    this.anonymity = true;
  }

  anonymity: boolean;
  displayName: string;
  numberOfVoice: number;
  voteType: VoteType;
  tallyTiming: TallyTiming;
  point: number;
  options = [new VoteOption('1'), new VoteOption('2')];
  questions = Array<QuestionCrtDto>();
}
```
무엇보다 테스트 코드도 편할거고 함수형 프로그래밍에 반 하지 않으니.. 좋겠네요
위위 코드 처럼, dto를 utility function을 써서 사용해 볼까요?

**Comment by tony3918** [comment]
> // Class 사용 시
> const editDto = new RingerUpdateDto(editRinger);
> setUpdateDto(editDto);

위에 이렇게 적어주셨는데 사실 여기서 `new RingerUpdateDto(editRinger);`라고 적었을 때의 저 `editRinger`도 결국 어디에선가는 `const editRinger = { ... };` 형태로 만들어진 것 아닌가요?!

그래서 진범님께서 
> class는 new Dto(data) 로 간단히 쓸 수 있지 않을까요. 매핑이 간단해 진다.

라고 해주셨는데 사실 단순 mapping function의 경우에는 아래 1,2번이 동일할 것 같아서요.
```
const sendRequest = (dto: IDto) => {...};

// 1번
const dto = new Dto(data);
sendRequest(dto);

// 2번
sendRequest(data);
```

Class로 했을 때 혼란스러울 수 있을 것 같다고 생각했던 부분은 나중에라도 js의 class가 OOP 언어의 것과 같지 않다는 것을 잘 모르는 분이 봤을 때 헷갈릴 수도 있지 않을까 싶었습니다 (저희가 사용하는 DTO에 추상화, 캡슐화, 상속, 다형성 같은 OOP 특성이 없음에도 class라고 명시적으로 쓰고 있으니까요). 그렇지만 생각해보니 이건 그렇게 문제가 될 것 같지는 않습니다.

---
> Data Transfer Object를 {} 로하냐, class 로 하냐인데....

결국 말씀해주신대로 기호의 차이일테니 하나로 정해서 가면 될 것 같습니다. 개인적으로는 매 번 mapping을 위한 class를 작성하는 것이 boilerplate 같아서 interface를 선호했는데, 팀의 결정에 따르겠습니다!

**Comment by jbjeong-sstk** [comment]
종택님과도 얘기 나눴는데.

공식적으론 dto 만들때 util 함수만들어서 사용하는거로 하죠?!

**Comment by tony3918** [comment]
네 알겠습니다!
